version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: this
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  your_service_name:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/resourcedb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    secrets:
      - aws_secrets
    depends_on:
      - mysql
    restart: always


volumes:
  mysql_data:

secrets:
  aws_secrets:
    file: secrets.env
